Group_ID :- SE/OOP/2023/S2/MLB/WD/G202
Group_Topic :- Online Food Ordering System

---------------Contribution--------------------

IT22053282 | Bogahawattege K.S

jsp   - addFood.jsp
      - ListFood.jsp
      - menu.jsp
      - review.jsp
      - updateFood.jsp

CRUD operation - Admin edit,update,delete,view food details
       
Servlet - UpdateFoodServlet.java
        - DeleteFoodServlet.java
        - ListFoodServlet.java
        - AddFoodServlet.java

CSS - review.css
    - listFood.css
    - menu.css

Interface - IFood.java

model - Food.java

DAO - foodDAO.java

Utility - DBConnection.java

database - Script.sql